TodoList/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include(("list.urls", "list"), namespace="list")),
]

list/urls.py
from django.urls import path
from list.views import (
    TaskListView,
    TagListView,
    TagsCreateView,
    TagsUpdateView,
    TagsDeleteView,
    TasksCreateView,
    TasksDeleteView,
    TasksUpdateView,
    change_task_status
)

urlpatterns = [
    path("", TaskListView.as_view(), name="task-list"),
    path("tags/", TagListView.as_view(), name="tag-list"),
    path("tags/create", TagsCreateView.as_view(), name="tag-create"),
    path("tags/<int:pk>/update", TagsUpdateView.as_view(), name="tag-update"),
    path("tags/<int:pk>/delete", TagsDeleteView.as_view(), name="tag-delete"),
    path("tasks/create", TasksCreateView.as_view(), name="task-create"),
    path("tasks/<int:pk>/delete", TasksDeleteView.as_view(), name="task-delete"),
    path("change_task_status/<int:pk>/", change_task_status, name="task-update-status"),
    path("tasks/<int:pk>/update/", TasksUpdateView.as_view(), name="task-update"),
]

list/models.py
from django.db import models


class Task(models.Model):
    content = models.TextField(max_length=255)
    date = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(blank=True, null=True)
    status = models.BooleanField(default=False)
    tags = models.ManyToManyField("Tag", related_name="tasks")

    class Meta:
        ordering = ["status", "-date"]

    def __str__(self):
        return self.content


class Tag(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

list/forms.py
from django import forms
from list.models import Tag, Task


class TagForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = "__all__"


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = "__all__"
        widgets = {
            'deadline': forms.DateInput(attrs={'type': 'date'})
        }

list/views.py
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views import generic

from list.forms import TagForm, TaskForm
from list.models import Task, Tag


class TaskListView(generic.ListView):
    model = Task
    context_object_name = 'task_list'


class TagListView(generic.ListView):
    model = Tag
    context_object_name = 'tag_list'


class TagsCreateView(generic.CreateView):
    model = Tag
    form_class = TagForm
    success_url = reverse_lazy('list:tags-list')


class TagsDeleteView(generic.DeleteView):
    model = Tag
    success_url = reverse_lazy('list:tags-list')


class TagsUpdateView(generic.UpdateView):
    model = Tag
    form_class = TagForm
    success_url = reverse_lazy('list:tags-list')


class TasksCreateView(generic.CreateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy('list:task-list')


class TasksDeleteView(generic.DeleteView):
    model = Task
    success_url = reverse_lazy('list:task-list')


class TasksUpdateView(generic.UpdateView):
    model = Task
    form_class = TaskForm


def change_task_status(request: HttpRequest, pk: int) -> HttpResponse:
    task = get_object_or_404(Task, pk=pk)
    task.status = not task.status
    task.save()
    return HttpResponseRedirect(reverse_lazy('list:task-list'))

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% block title %}<title>TODO list</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
          crossorigin="anonymous">
</head>

<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2 sidebar">
            {% block sidebar %}
                {% include "includes/sidebar.html" %}
            {% endblock %}
        </div>
        <div class="col-sm-10 content">
            <div class="content-inner">
                {% block content %}{% endblock %}
            </div>
        </div>
    </div>
</div>
</body>
</html>

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  <li class="list-group-item"><a href="{% url "list:task-list" %}" class="text-dark"><i class="fas fa-home mr-2"></i>Home</a></li>
  <li class="list-group-item"><a href="{% url "list:tag-list" %}" class="text-dark"><i class="fas fa-tags mr-2"></i>Tags</a></li>
</ul>

templates/list/index.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
<div class="container">
  <h1 class="mt-5">TODO list</h1>
  <a href="{% url "list:task-create" %}" class="btn btn-primary mb-3"><i class="fas fa-plus"></i> Add task</a>
  <ul class="list-group mt-3">
    {% for task in tasks %}
    <li class="list-group-item">
      <div class="row">
        <div class="col-6">
          <span class="font-weight-bold">{{ task.content }}</span>
          {% if task.status == True %} 
          <span class="badge badge-success">Complete</span>
          {% else %}
           <span class="badge badge-warning">In progress</span>
          {% endif %}
        </div>
        <div class="col-6 text-right">
          <small>{{ task.date }} - {{ task.deadline }}</small>
          {% if task.status == False %}
          <a href="{% url "list:task-update-status" task.id %}" class="btn btn-primary btn-sm"><i class="fas fa-edit"></i>Complete</a>
          {% else %}
          <a href="{% url "list:task-delete" task.id %}" class="btn btn-warning btn-sm"><i class="fas fa-edit"></i>Undo</a>
          {% endif %}
        </div>
      </div>
      <div class="row mt-2">
        <div class="col-12">
        Tags:
          {% for tag in  task.tags.all%}
              {{ tag }}
            {% endfor %}
         <a href="{% url "list:task-update"  pk=task.id %}">Update</a> <a href="{% url "list:task-delete"  pk=task.id %}">Delete</a>
        </div>
      </div>
    </li>
    {% endfor %}
  </ul>
</div>
{% endblock %}

templates/list/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete tag?</h1>
  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/list/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
 <h1>{{ object|yesno:"Update,Create" }} Tag</h1>
  <form action="" method="post">
  {% csrf_token %}
    {{ form.name|as_crispy_field }}

    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
{% endblock %}

templates/list/tag_list.html
{% extends "base.html" %}

{% block content %}
<div class="container">
  <h1 class="mt-5">Tags</h1>
  <a href="{% url "list:tag-create" %}" class="btn btn-primary mb-3"><i class="fas fa-plus"></i> Add tag</a>
  {% if tag_list %}
    <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col">Name</th>
          <th scope="col">Update</th>
          <th scope="col">Delete</th>
        </tr>
      </thead>
      <tbody>
      {% for tag in tag_list %}
        <tr>
          <td>{{ tag.name }}</td>
          <td>
            <a href="{% url "list:tag-update" pk=tag.id %}" class="btn btn-sm btn-warning"><i class="fas fa-edit"></i> Update</a>
          </td>
          <td>
            <a href="{% url "list:tag-delete" pk=tag.id %}" class="btn btn-sm btn-danger"><i class="fas fa-trash-alt"></i> Delete</a>
          </td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
  {% else %}
    <p>No tags to display</p>
  {% endif %}
</div>
{% endblock %}

templates/list/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete task?</h1>
  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/list/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
 <h1>{{ object|yesno:"Change status of,Create" }} Task</h1>
  <form action="" method="post">
  {% csrf_token %}
    {{ form|crispy }}

    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
{% endblock %}

templates/list/task_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
<div class="container">
  <h1 class="mt-5">TODO list</h1>
  <a href="{% url "list:task-create" %}" class="btn btn-primary mb-3"><i class="fas fa-plus"></i> Add task</a>
  <ul class="list-group mt-3">
    {% for task in task_list %}
    <li class="list-group-item">
      <div class="row">
        <div class="col-6">
          <span class="font-weight-bold">{{ task.content }}</span>
          {% if task.status == True %} 
          <span class="badge badge-success">Complete</span>
          {% else %}
           <span class="badge badge-warning">In progress</span>
          {% endif %}
        </div>
        <div class="col-6 text-right">
          <small>{{ task.date }} - {{ task.deadline }}</small>
          {% if task.status %}
          <a href="{% url "list:task-update-status" task.id %}" class="btn btn-primary btn-sm"><i class="fas fa-edit"></i>Undo</a>
          {% else %}
          <a href="{% url "list:task-update-status" task.id %}" class="btn btn-warning btn-sm"><i class="fas fa-edit"></i>Complete</a>
          {% endif %}
        </div>
      </div>
      <div class="row mt-2">
        <div class="col-12">
        Tags:
          {% for tag in  task.tags.all%}
              {{ tag }}
            {% endfor %}
         <a href="{% url "list:task-update"  pk=task.id %}">Update</a> <a href="{% url "list:task-delete"  pk=task.id %}">Delete</a>
        </div>
      </div>
    </li>
    {% endfor %}
  </ul>
</div>
{% endblock %}